M48
; DRILL file {KiCad (6.0.5)} date Wed Jun 29 19:51:04 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-29T19:51:04+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
%
G90
G05
T1
X5.412Y-3.4
X5.412Y-3.9
X5.412Y-4.4
X5.6876Y-3.4
X5.6876Y-3.9
X5.6876Y-4.4
X6.7124Y-3.9
X6.988Y-3.9
T0
M30
